[[language]]
name = "dafny"
scope = "source.dfy"
file-types = ["dfy"]
language-servers = ["dafny-server"]
comment-tokens = []

[language-server.dafny-server]
command = "dafny"
args = ["server", "--stdin"]

[[language]]
name = "rust"
[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", initCommands = [ "command script import /opt/homebrew/Cellar/rust/1.71.0/lib/rustlib/etc/lldb_lookup.py", "command source -s 0 /opt/homebrew/Cellar/rust/1.71.0/lib/rustlib/etc/lldb_commands" ] }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
language-servers = [ "pyright" ]
auto-format = true
formatter = {command = "black", args = ["-",  "--quiet","--line-length=100",]}

# [[language]]
# name = "latex"
# 
# [language.config.texlab]
# auxDirectory = "build"
# 
# [language.config.texlab.chktex]
# onOpenAndSave = true
# onEdit = true
# 
# [language.config.texlab.forwardSearch]
# executable = "zathura"
# args = [ "--synctex-forward", "%l:%c:%f", "%p" ]
# 
# # executable = "okular"
# # args = ["--unique", "file:%p#src:%l%f"]
# 
# [language.config.texlab.build]
# forwardSearchAfter = true
# onSave = true
# 
# # executable = "latexmk"
# # args = [
# #  "-pdf",
# #  "-interaction=nonstopmode",
# #  "-synctex=1",
# #  "-shell-escape",
# #  "-output-directory=build",
# #  "%f"
# #  ]
# 
# executable = "tectonic"
# args = [
#  "-X",
#  "compile",
#  "%f",
#  "--synctex",
#  "--keep-logs",
#  "--keep-intermediates",
#  "--outdir=build",
#  "-Zshell-escape",
#  ]
# 
# 
